version: "3.1"
services:
  backend:
    build: ./backend
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/code

  frontend:
    build: ./frontend
    # depends_on:
    #   - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/code
